name: Dev Testing 🔎

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev-testing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" > .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env

      - name: Build and start PacMusic Dev
        run: sudo docker compose up --build --detach pacmusic-dev

      - name: Wait for the app to start
        run: sleep 10

      - name: Test application endpoint
        run: curl http://localhost:5000

      # - name: Install testing requirements
      #   run: pip install -r test/requirements.txt

      # - name: Run tests
      #   run: python3 test/test.py
